services:
  - type: web
    name: moonlord-backend
    env: node
    plan: free
    buildCommand: "npm install --prefix backend"
    startCommand: "npm run start --prefix backend"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: moonlord-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
    autoDeploy: true

  - type: web
    name: moonlord-frontend
    env: static
    buildCommand: "npm install --prefix frontend && npm run build --prefix frontend"
    staticPublishPath: "frontend/dist"
    autoDeploy: true
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"

databases:
  - name: moonlord-db
    plan: free
    
